backend:
  name: git-gateway
  repo: heaven-prophetic/home
  branch: main # or "master"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "sermons"
    label: "Sermons"
    folder: "data/sermons"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Speaker", name: "speaker", widget: "string" }
      - { label: "YouTube URL", name: "youtube", widget: "string", required: false }
      - { label: "Facebook URL", name: "facebook", widget: "string", required: false }
      - { label: "Is Live?", name: "live", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: required: false }


  - name: "events"
    label: "Events"
    folder: "data/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: required: false }
